"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var React = require("react");
var react_redux_1 = require("react-redux");
var Home = function () { return (React.createElement("div", null,
    React.createElement("h1", null, "Hello! Welcome to CarSales MVP by Avtar Singh."),
    React.createElement("p", null, "Welcome to your new single-page application, built with:"),
    React.createElement("ul", null,
        React.createElement("li", null,
            React.createElement("a", { href: 'https://get.asp.net/' }, "ASP.NET Core"),
            " and ",
            React.createElement("a", { href: 'https://msdn.microsoft.com/en-us/library/67ef8sbd.aspx' }, "C#"),
            " for cross-platform server-side code"),
        React.createElement("li", null,
            React.createElement("a", { href: 'https://facebook.github.io/react/' }, "React"),
            " and ",
            React.createElement("a", { href: 'https://redux.js.org/' }, "Redux"),
            " for client-side code"),
        React.createElement("li", null,
            React.createElement("a", { href: 'http://getbootstrap.com/' }, "Bootstrap"),
            " for layout and styling")),
    React.createElement("p", null, "To help you get started, we've also set up:"),
    React.createElement("ul", null,
        React.createElement("li", null,
            React.createElement("strong", null, "Client-side navigation"),
            ". For example, click ",
            React.createElement("em", null, "Cars"),
            " then ",
            React.createElement("em", null, "Back"),
            " to return here."),
        React.createElement("li", null, "Please change the \"appDbConnection\" string in \"appsettings.json\" to your local database.")),
    React.createElement("p", null,
        "The ",
        React.createElement("code", null, "ClientApp"),
        " subdirectory is a standard React application. If you open a command prompt in that directory, you can run ",
        React.createElement("code", null, "npm"),
        " commands such as ",
        React.createElement("code", null, "npm test"),
        " or ",
        React.createElement("code", null, "npm install"),
        "."))); };
exports.default = react_redux_1.connect()(Home);
//# sourceMappingURL=Home.js.map